default: &default
  # Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
  secret_key_base: <%= BentOS::Config.secret_key %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
